src/Entity/Maintenance.php
<?php

namespace App\Entity;

use App\Repository\MaintenanceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MaintenanceRepository::class)]
class Maintenance
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'maintenances')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Application $application = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startingDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endingDate = null;

    #[ORM\Column(length: 255)]
    private ?string $applicationState = null;

    #[ORM\Column]
    private ?bool $isArchived = false;

    #[ORM\OneToMany(targetEntity: MaintenanceHistory::class, mappedBy: 'Maintenance')]
    private Collection $maintenanceHistories;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Message = null;

    public function __construct()
    {
        $this->maintenanceHistories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getApplication(): ?Application
    {
        return $this->application;
    }

    public function setApplication(?Application $application): static
    {
        $this->application = $application;

        return $this;
    }

    public function getStartingDate(): ?\DateTimeInterface
    {
        return $this->startingDate;
    }

    public function setStartingDate(\DateTimeInterface $startingDate): static
    {
        $this->startingDate = $startingDate;

        return $this;
    }

    public function getEndingDate(): ?\DateTimeInterface
    {
        return $this->endingDate;
    }

    public function setEndingDate(\DateTimeInterface $endingDate): static
    {
        $this->endingDate = $endingDate;

        return $this;
    }

    public function getApplicationState(): ?string
    {
        return $this->applicationState;
    }

    public function setApplicationState(string $applicationState): static
    {
        $this->applicationState = $applicationState;

        return $this;
    }

    public function isIsArchived(): ?bool
    {
        return $this->isArchived;
    }

    public function setIsArchived(bool $isArchived): static
    {
        $this->isArchived = $isArchived;

        return $this;
    }

    /**
     * @return Collection<int, MaintenanceHistory>
     */
    public function getMaintenanceHistories(): Collection
    {
        return $this->maintenanceHistories;
    }

    public function addMaintenanceHistory(MaintenanceHistory $maintenanceHistory): static
    {
        if (!$this->maintenanceHistories->contains($maintenanceHistory)) {
            $this->maintenanceHistories->add($maintenanceHistory);
            $maintenanceHistory->setMaintenance($this);
        }

        return $this;
    }

    public function removeMaintenanceHistory(MaintenanceHistory $maintenanceHistory): static
    {
        if ($this->maintenanceHistories->removeElement($maintenanceHistory)) {
            // set the owning side to null (unless already changed)
            if ($maintenanceHistory->getMaintenance() === $this) {
                $maintenanceHistory->setMaintenance(null);
            }
        }

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(?string $Message): static
    {
        $this->Message = $Message;

        return $this;
    }
}

templates/maintenance_form/index.html.twig
{% extends 'edit.html.twig' %}

{% block body %}

            {{ form_start(maintenanceForm) }}
            <div class="row mt-3">
                <div class="col-3">
                    <h6 class="text-end">Application<span class="text-danger">*</span></h6>
                </div>
                <div class="col-7 col-xl-3 pe-md-5">
                    {{ form_widget(maintenanceForm.application, {'attr': {'class': 'form-control rounder text-center'}}) }}
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-3">
                    <h6 class="text-end">État pendant l'opération<span class="text-danger">*</span></h6>
                </div>
                <div class="col-7 col-xl-3 pe-md-5">
                    {{ form_widget(maintenanceForm.applicationState, {'attr': {'class': 'form-select rounder text-center'}}) }}
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-3">
                    <h6 class="text-end">Début prévu<span class="text-danger">*</span></h6>
                </div>
                <div class="col-7 col-xl-3 pe-md-5">
                    <div class="text-danger meteo-maintenance-errors">
                        {{ form_errors(maintenanceForm.startingDate) }}
                    </div>
                    {{ form_widget(maintenanceForm.startingDate, {'attr': {'class': 'd-inline form-control rounded text-center pe-5'}}) }}
                    {#{ ajout d'une icone avec des marges négatives pour cliquer sur le calendrier (idem pour endingDate mais je remet pas ce commentaire) }#}
                    <i class="dtipicker d-inline m-n4 m-md-n5 bi bi-calendar"></i>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-3">
                    <h6 class="text-end">Fin prévue<span class="text-danger">*</span></h6>
                </div>
                <div class="col-7 col-xl-3 pe-md-5 me-n4">
                    <div class="text-danger meteo-maintenance-errors">
                        {{ form_errors(maintenanceForm.endingDate) }}
                    </div>
                    {{ form_widget(maintenanceForm.endingDate, {'attr': {'class': 'd-inline form-control rounder text-center pe-5'}}) }}
                    <i class="dtipicker d-inline m-n4 m-md-n5 bi bi-calendar"></i>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-3">
                    <h6 class="text-end">Détail de la maintenance</h6>
                </div>
                <div class="col-7 col-xl-3 pe-md-5">
                    {{ form_widget(maintenanceForm.message, {'attr': {'class': 'form-control rounder text-center'}}) }}
                    <div class="text-danger">
                        {{ form_errors(maintenanceForm.message) }}
                    </div>
                </div>
            </div>
            <div class="row mt-1">
                <div class="col-6 offset-3 offset-lg-0">
                    <div class="d-flex justify-content-end">Les champs marqués d'un astérisque rouge sont
                        obligatoires.
                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-3"></div>
                <div class="col-6">
                    <button type="submit" id="save" class="shadow px-3 py-2 rounded-pill border-0 text-center"><b>Sauvegarder</b></button>
                </div>
            </div>
            {{ form_end(maintenanceForm) }}
        </div>

    </div>
{% endblock %}